# -*- coding: utf-8 -*-
"""CIE-4

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1On5tmR3b2op8TfwAYacP-qrzkG1fpm1s
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans

data=pd.read_csv('/content/Mall_Customers (1).csv')
data.head()

x = data.iloc[:, [3, 4]].values
x

data.shape

data.info()

data.isnull().sum()

wcss_list= []
for i in range(1, 11):
  kmeans = KMeans(n_clusters=i, init='k-means++', random_state= 42)
  kmeans.fit(x)
  wcss_list.append(kmeans.inertia_)
plt.plot(range(1, 11), wcss_list)
plt.title('The Elobw Method Graph')
plt.xlabel('Number of clusters(k)')
plt.ylabel('wcss_list')
plt.show()

kmeans = KMeans(n_clusters=5, init='k-means++', random_state= 42)
y_predict= kmeans.fit_predict(x)
y_predict

plt.scatter(x[y_predict == 0, 0], x[y_predict == 0, 1], s = 100, c = 'b',
label = 'C luster 1')
plt.scatter(x[y_predict == 1, 0], x[y_predict == 1, 1], s = 100, c = 'r',
label = ' Cluster 2')
plt.scatter(x[y_predict== 2, 0], x[y_predict == 2, 1], s = 100, c = 'g',
label = 'Clu ster 3')
plt.scatter(x[y_predict == 3, 0], x[y_predict == 3, 1], s = 100, c = 'cyan',
label = 'C luster 4')
plt.scatter(x[y_predict == 4, 0], x[y_predict == 4, 1], s = 100, c ='magenta', label = 'Cluster 5')
plt.scatter(kmeans.cluster_centers_[:, 0], kmeans.cluster_centers_[:, 1], s= 300, c = 'yellow', label = 'Centroid')
plt.title('Clusters of customers')
plt.xlabel('Annual Income (k$)')
plt.ylabel('Spending Score (1-100)')
plt.legend()
plt.show()